blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    # path('', views.post_list, name='post_list'),
    # path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.PostListView.as_view(), name='post_list_by_tag'),
    path('post/<int:pk>-<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),   

    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),

    # path('post/add/', views.PostCreateView.as_view(), name='post_create'),
    # path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    # path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/add/', views.PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>-<slug:slug>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>-<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('account/', include('account.urls')),
    path('api/', include('blog.api.urls', namespace='api')),
    path('api_auth/', include('rest_framework.urls')),
    path('reference/', include('reference.urls')),
    path('apireference/', include('reference.api.urls', namespace='apireference')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

reference/api/urls.py
from django.urls import path
from . import views

app_name = 'reference'
urlpatterns = [
    path('references/', views.ReferenceListView.as_view(), name='api_reference_list'),
    path('references/<int:pk>/', views.ReferenceDetailView.as_view(), name='api_reference_detail'),
]

reference/urls.py
from django.urls import path
from . import views

app_name = 'reference'
urlpatterns = [
    path('', views.reference_list, name='reference_list'),
    path('references/add/', views.ReferenceCreateView.as_view(), name='reference_create'),
    path('references/<int:pk>/update/', views.ReferenceUpdateView.as_view(), name='reference_update'),
    path('references/<int:pk>/delete/', views.ReferenceDeleteView.as_view(), name='reference_delete'),
]

reference/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse_lazy

# Create your models here.
class Reference(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    link = models.URLField(max_length=250)
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name='reference_posts')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    #status =  models.CharField(max_length=10, choices = STATUS_CHOICES, default='draft')

    objects = models.Manager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     # return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])
    #     return reverse_lazy('blog:post_detail', kwargs={'pk':self.id, 'slug':self.slug})

reference/api/views.py
from rest_framework import generics, mixins, permissions
from ..models import Reference
from .serializers import ReferenceSerializer
from .permissions import IsAuthorOrReadOnly

class ReferenceListView(generics.ListCreateAPIView):
    queryset = Reference.objects.all()
    serializer_class = ReferenceSerializer

    #permission----
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def perform_create(self, serializer):
        if serializer.is_valid():
            serializer.save(author=self.request.user)

class ReferenceDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Reference.objects.all()
    serializer_class = ReferenceSerializer
    #permission----
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsAuthorOrReadOnly]

    def perform_update(self, serializer):
        if serializer.is_valid():
            serializer.save()

reference/views.py
from django.shortcuts import render
from .models import Reference
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.
@login_required
def reference_list(request):
    # references = Reference.objects.all()
    object_list = Reference.objects.all()

    paginator = Paginator(object_list, 2)
    page = request.GET.get('page')

    try:
        references = paginator.page(page)
    except PageNotAnInteger:
        references = paginator.page(1)
    except EmptyPage:
        references = paginator.page(paginator.num_pages)

    return render(request, 'reference/post/list.html', {'page':page, 'references' : references})

# class ReferenceListView(LoginRequiredMixin, ListView):
#     queryset = Reference.published.all()
#     context_object_name = 'references'
#     paginate_by = 2
#     template_name = 'reference/post/list.html'

#     def get_queryset(self):
#         qs = super().get_queryset()
        
#         return qs
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         if self.tag:
#             context['tag'] = self.tag
#         return context

class ReferenceCreateView(LoginRequiredMixin, CreateView):
    model = Reference
    # fields = ['title', 'slug', 'author', 'body', 'tags', 'status']
    fields = ['title', 'description', 'link']
    template_name = 'reference/post/reference_form.html'
    success_url = reverse_lazy('reference:reference_list')

    def form_valid(self, form):
        form.instance.author = self.request.user

        return super().form_valid(form)


class ReferenceUpdateView(LoginRequiredMixin, UpdateView):
    model = Reference
    fields = ['title', 'description', 'link']
    template_name = 'reference/post/reference_form.html'
    success_url = reverse_lazy('reference:reference_list')

    query_pk = True

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(author = self.request.user)

    def form_valid(self, form):
        return super().form_valid(form)

class ReferenceDeleteView(LoginRequiredMixin, DeleteView):
    model = Reference
    template_name = 'reference/post/reference_confirm_delete.html'
    success_url = reverse_lazy('reference:reference_list')
    query_pk = True

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(author = self.request.user)    

reference/templates/reference/post/latest_post_reference.html
<ul>
    
    {% for reference in latest_references %}
        <li>
            {{reference.title}}
        </li>
    {% endfor %}
        
</ul>

reference/templates/reference/post/list.html
{% extends 'blog/base.html' %}
{% block title %}
    Blog-References
{% endblock title %}

{% block content %}
    <h1>References</h1>
        
    {% for reference in references %}
        <h2>
                {{reference.title}}
        </h2> 
        <p class="date">
            Published {{reference.publish}} by {{reference.author}}
        </p>
        Description : {{reference.description|truncatewords:30|linebreaks }}
        Link : <a href="{{reference.link}}" target="blank">{{reference.link|linebreaks}}</a>
        <p>
            {% if reference.author == request.user %}
                <a href="{% url 'reference:reference_update' reference.id %}">Update</a> | 
                <a href="{% url 'reference:reference_delete' reference.id %}">Delete</a>
            {% endif %}
        </p>
    {% endfor %}

    {% include "pagination.html" with page=references %}
{% endblock content %}

reference/templates/reference/post/reference_confirm_delete.html
{% extends 'blog/base.html' %}
{% block title %}
    Delete Reference
{% endblock title %}

{% block content %}
    <h1>Delete Reference</h1>
    <form action="" method="post">
        <p>Are you sure want to delete this item <strong>{{object}}</strong> ? </p>
        {% csrf_token %}
        <p><input type="submit" value="Confirm Delete"></p>
    </form>
{% endblock content %}
    

reference/templates/reference/post/reference_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create/Update Reference
{% endblock title %}

{% block content %}
    <h1>
        {% if 'add' in request.path|slice:'-7:' %}
            Create Request       
        {% else %}
            Update Request
        {% endif %}
    </h1>
    <form action="" method="post">
        <!-- {{form.as_p}} -->
        
        {% for field in form  %}
            <div class="row">
                <div class="col">
                    {{ field|as_crispy_field }}
                </div>
            </div>
        {% endfor %}
            
        {% csrf_token %}
        <br>
        <p>
            <!-- <input type="submit" value="Create/Update"> -->
            <input type="submit" value="{% if 'add' in request.path|slice:'-7:' %}Create{% else %}Update{% endif %}" 
            class="btn btn-primary">
        </p>
    </form>
{% endblock content %}
    